### ISSUE TITLE
Debug DisplayView color doesn't match the syntax

### ISSUE THREAD

**Issue by gayanper** [gayanper/eclipse-themes#1]
Add the following style to css to fix the background color
````css
#org-eclipse-jdt-debug-ui-DisplayView StyledText {
	background-color: <styled text bg color in dark and light themes>;
}
````
